apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/baremetal/deploy.yaml
- ingress-service-metrics.yml

patchesJson6902:
- path: deployment-patch.yml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx

- path: service-patch.yml
  target:
    version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx

- path: ingress-config-patch.yml
  target:
    version: v1
    kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
